#usar para el comando

command_name: "rename"
command_description: "§rChange the name of the hand item"
usage_command: "§cUsage /{label} (new name)"

#mensajes del comando
only_player: "§cYou can only use this command in the server"
need_permission: "§cYou don't have permission to use the command!"
item_rename: "§cNew item name is » {itemname}"
item_null: "§cYou don't have any item in hand"
